CREATE TABLE PUNTAJES_JUEGO (
    ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JUGADOR   VARCHAR2(100),
    PUNTAJE   NUMBER,
    FECHA     DATE DEFAULT SYSDATE
);

-- Procedimiento para insertar puntaje
CREATE OR REPLACE PROCEDURE INSERTAR_PUNTAJE(
    P_JUGADOR IN VARCHAR2,
    P_PUNTAJE IN NUMBER
)
AS
BEGIN
    INSERT INTO PUNTAJES_JUEGO (JUGADOR, PUNTAJE)
    VALUES (P_JUGADOR, P_PUNTAJE);

    COMMIT;
END;
/

COMMIT;